### ISSUE TITLE
Error installing Dan::Pandas

### ISSUE THREAD

**Issue by kapitaali** [librasteve/raku-Dan-Pandas#5] opened 2022-06-07 18:01 UTC
Installing Dan::Pandas from zef on Debian Linux 5.17.0-1-amd64 #1 SMP PREEMPT Debian 5.17.3-1 (2022-04-18) x86_64 GNU/Linux running Rakudo™ v2021.10 (on Lenovo x220):

```
zef install Dan::Pandas
===> Searching for: Dan::Pandas
===> Testing: Dan::Pandas:ver<0.0.1>:auth<zef:p6steve>:api<1>
[Dan::Pandas] ===SORRY!=== Error while compiling /home/theb/.zef/tmp/bbcf7eac460343f83da4808650e7a9d5f6ee6493.tar.gz/dist/t
[Dan::Pandas] /01-ser.t
[Dan::Pandas] ===SORRY!=== Error while compiling /home/theb/.zef/tmp/bbcf7eac460343f83da4808650e7a9d5f6ee6493.tar.gz/dist/lib/Dan/Pandas.rakumod (Dan::Pandas)
[Dan::Pandas] Invalid typename 'Dan::Series' in parameter declaration.
[Dan::Pandas] at /home/theb/.zef/tmp/bbc
[Dan::Pandas] f7eac460343f83da4808650e7a9d5f6ee6493.tar.gz/dist/lib/Dan/Pandas.rakumod (Dan::Pandas):73
[Dan::Pandas] ------>     multi method new( Dan::Series:D⏏ \s ) {
[Dan::Pandas]     expecting any of:
[Dan::Pandas]         pair value
[Dan::Pandas] 
[Dan::Pandas] at /home/theb/.zef/tmp/bbcf7eac460343f83da4808650e7a9d5f6ee6493.tar.gz/dist/t/01-ser.t:9
===> Testing [FAIL]: Dan::Pandas:ver<0.0.1>:auth<zef:p6steve>:api<1>
Aborting due to test failure: Dan::Pandas:ver<0.0.1>:auth<zef:p6steve>:api<1> (use --force-test to override)

```

zef info Dan says the following:
```
- Info for: Dan
- Identity: Dan:ver<0.0.1>:auth<zef:p6steve>:api<1>
- Recommended By: Zef::Repository::LocalCache
- Installed: Yes
Description:	 Top level roles for Data Analytics.
License:	 Artistic-2.0
Source-url:	 git://github.com/p6steve/raku-dan.git
Provides: 1 modules
Depends: 1 items
```

**Comment by kapitaali** [comment] 2022-06-07 18:13
Verbosely running zef install produces the following:

```
zef install --verbose --force-install --force-test https://github.com/p6steve/raku-Dan-Pandas.git
===> Fetching [OK]: https://github.com/p6steve/raku-Dan-Pandas.git to /home/theb/.zef/tmp/1654625077.34340.1112.2744593193245/raku-Dan-Pandas.git
===> Extraction [OK]: https://github.com/p6steve/raku-Dan-Pandas.git to /home/theb/.zef/tmp/raku-Dan-Pandas.git
The following uri candidates are already installed: https://github.com/p6steve/raku-Dan-Pandas.git
===> Testing: Dan::Pandas:ver<0.0.1>:auth<zef:p6steve>:api<1>
[Dan::Pandas] ===SORRY!=== Error while compiling /home/theb/.zef/tmp/raku-Dan-Pandas.git/b45b4561f4c0f68a72955e8ad5fc023a75
[Dan::Pandas] 24d8d9/t/01-ser.t
[Dan::Pandas] ===SORRY!=== Error while compiling /home/theb/.zef/tmp/raku-Dan-Pandas.git/b45b4561f4c0f68a72955e8ad5fc023a7524d8d9/lib/Dan/Pandas.rakumod (Dan::Pandas)
[Dan::Pandas] Redeclaration of routine 'sbv'.  Did you mean to declare a multi-su
[Dan::Pandas] b?
[Dan::Pandas] at /home/theb/.zef/tmp/raku-Dan-Pandas.git/b45b4561f4c0f68a72955e8ad5fc023a7524d8d9/lib/Dan/Pandas.rakumod (Dan::Pandas):17
[Dan::Pandas] ------> }⏏<EOL>
[Dan::Pandas] 
[Dan::Pandas] at /home/theb/.zef/tmp/raku-Dan-Pandas.git/b45b4561f4c0f68a72955e8ad5fc023a7524d8d9/t/01-ser.t:9
[Dan::Pandas] t/01-ser.t .. Dubious, test returned 1
[Dan::Pandas] No subtests run
[Dan::Pandas] t/02-dfr.t .. Dubious, test returned 1
[Dan::Pandas] No subtests run
[Dan::Pandas] t/03-dfo.t .. Dubious, test returned 1
[Dan::Pandas] Failed 1/26 subtests 
[Dan::Pandas] t/04-upd.t .. Dubious, test returned 1
[Dan::Pandas] No subtests run
[Dan::Pandas] 
[Dan::Pandas] Test Summary Report
[Dan::Pandas] -------------------
[Dan::Pandas] t/01-ser.t (Wstat: 256 Tests: 0 Failed: 0)
[Dan::Pandas] Non-zero exit status: 1
[Dan::Pandas]   Parse errors: No plan found in TAP output
[Dan::Pandas] t/02-dfr.t (Wstat: 256 Tests: 0 Failed: 0)
[Dan::Pandas] Non-zero exit status: 1
[Dan::Pandas]   Parse errors: No plan found in TAP output
[Dan::Pandas] t/03-dfo.t (Wstat: 256 Tests: 25 Failed: 1)
[Dan::Pandas]   Failed tests:  23
[Dan::Pandas] Non-zero exit status: 1
[Dan::Pandas]   Parse errors: Bad plan.  You planned 26 tests but ran 25.
[Dan::Pandas] t/04-upd.t (Wstat: 256 Tests: 0 Failed: 0)
[Dan::Pandas] Non-zero exit status: 1
[Dan::Pandas]   Parse errors: No plan found in TAP output
[Dan::Pandas] Files=4, Tests=25,  10 wallclock secs
[Dan::Pandas] Result: FAILED
===> Testing [FAIL]: Dan::Pandas:ver<0.0.1>:auth<zef:p6steve>:api<1>
[Dan::Pandas] Failed to get passing tests, but continuing with --force-test
===> Installing: Dan::Pandas:ver<0.0.1>:auth<zef:p6steve>:api<1>
===> Install [FAIL] for Dan::Pandas:ver<0.0.1>:auth<zef:p6steve>:api<1>: ===SORRY!=== Error while compiling /home/theb/Videos/site#sources/A0EFFE63B40BC04CD8EB78CDCC7B22971E653B3A (Dan::Pandas)
Redeclaration of routine 'sbv'.  Did you mean to declare a multi-sub?
at /home/theb/Videos/site#sources/A0EFFE63B40BC04CD8EB78CDCC7B22971E653B3A (Dan::Pandas):17
------> }⏏<EOL>

===SORRY!=== Error while compiling /home/theb/Videos/site#sources/A0EFFE63B40BC04CD8EB78CDCC7B22971E653B3A (Dan::Pandas)
Redeclaration of routine 'sbv'.  Did you mean to declare a multi-sub?
at /home/theb/Videos/site#sources/A0EFFE63B40BC04CD8EB78CDCC7B22971E653B3A (Dan::Pandas):17
------> }⏏<EOL>

```

**Comment by librasteve** [comment] 2022-06-08 07:53
reproduced on my system

[Dan::Pandas] ===SORRY!=== Error while compiling /home/jovyan/.zef/tmp/bbcf7eac460343f83da4808650e7a9d5f6ee6493.tar.gz/dist/t/01-ser.t
[Dan::Pandas] ===SORRY!=== Error while compiling /home/jovyan/.zef/tmp/bbcf7eac460343f83da4808650e7a9d5f6ee6493.tar.gz/dist/lib/Dan/Pandas.rakumod (Dan::Pandas)
[Dan::Pandas] Invalid typename 'Dan::Series' in parameter declaration.
[Dan::Pandas] at /home/jovyan/.zef/tmp/bbcf7eac460343f83da4808650e7a9d5f6ee6493.tar.gz/dist/lib/Dan/Pandas.rakumod (Dan::Pandas):73
[Dan::Pandas] ------>     multi method new( Dan::Series:D⏏ \s ) {
[Dan::Pandas]     expecting any of:
[Dan::Pandas]         pair value
[Dan::Pandas] at /home/jovyan/.zef/tmp/bbcf7eac460343f83da4808650e7a9d5f6ee6493.tar.gz/dist/t/01-ser.t:9
[Dan::Pandas] t/01-ser.t .. 
[Dan::Pandas] Dubious, test returned 1 (wstat 256, 0x100)

**Comment by librasteve** [comment] 2022-06-08 07:55
works ok if install Dan::Pandas directly from github

base) root@e4a956a998d8:~# zef --verbose install https://github.com/p6steve/raku-Dan-Pandas.git
===> Fetching [OK]: https://github.com/p6steve/raku-Dan-Pandas.git to /home/jovyan/.zef/tmp/1654674912.416.4570.474165720862/raku-Dan-Pandas.git
===> Extraction [OK]: https://github.com/p6steve/raku-Dan-Pandas.git to /home/jovyan/.zef/tmp/raku-Dan-Pandas.git
===> Testing: Dan::Pandas:ver<0.0.1>:auth<zef:p6steve>:api<1>
[Dan::Pandas] t/01-ser.t .. ok
[Dan::Pandas] t/02-dfr.t .. ok
[Dan::Pandas] t/03-dfo.t .. ok
[Dan::Pandas] WARNING: unhandled Failure detected in DESTROY. If you meant to ignore it, you can mark it as handled by calling .Bool, .so, .not, or .defined methods. The Failure was:
[Dan::Pandas] No such symbol '<class 'numpy.int64'>'
[Dan::Pandas]   in block  at /home/jovyan/.zef/tmp/raku-Dan-Pandas.git/b45b4561f4c0f68a72955e8ad5fc023a7524d8d9/lib/Dan/Pandas.rakumod (Dan::Pandas) line 535
[Dan::Pandas]   in block  at /home/jovyan/.zef/tmp/raku-Dan-Pandas.git/b45b4561f4c0f68a72955e8ad5fc023a7524d8d9/lib/Dan/Pandas.rakumod (Dan::Pandas) line 533
[Dan::Pandas]   in block  at /home/jovyan/.zef/tmp/raku-Dan-Pandas.git/b45b4561f4c0f68a72955e8ad5fc023a7524d8d9/lib/Dan/Pandas.rakumod (Dan::Pandas) line 530
[Dan::Pandas]   in method TWEAK at /home/jovyan/.zef/tmp/raku-Dan-Pandas.git/b45b4561f4c0f68a72955e8ad5fc023a7524d8d9/lib/Dan/Pandas.rakumod (Dan::Pandas) line 516
[Dan::Pandas]   in method new at /home/jovyan/.zef/tmp/raku-Dan-Pandas.git/b45b4561f4c0f68a72955e8ad5fc023a7524d8d9/lib/Dan/Pandas.rakumod (Dan::Pandas) line 380
[Dan::Pandas]   in block <unit> at t/04-upd.t line 32
[Dan::Pandas] t/04-upd.t .. ok
[Dan::Pandas] All tests successful.
[Dan::Pandas] Files=4, Tests=104,  5 wallclock secs ( 0.01 usr  0.00 sys +  5.22 cusr  0.25 csys =  5.48 CPU)
[Dan::Pandas] Result: PASS
===> Testing [OK] for Dan::Pandas:ver<0.0.1>:auth<zef:p6steve>:api<1>
===> Installing: Dan::Pandas:ver<0.0.1>:auth<zef:p6steve>:api<1>
===> Install [OK] for Dan::Pandas:ver<0.0.1>:auth<zef:p6steve>:api<1>

**Comment by librasteve** [comment] 2022-06-08 07:56
note IGNORE the WARNING: unhandled Failure detected in DESTROY

**Comment by librasteve** [comment] 2022-06-08 07:58
synopsis-dan-pandas.raku runs OK (IGNORE same warning)
```
3 bin/ scripts [test.csv synopsis-dan-pandas.raku test.json] installed to:
/usr/share/perl6/site/bin
(base) root@e4a956a998d8:~# cd /usr/share/perl6/site/bin
(base) root@e4a956a998d8:/usr/share/perl6/site/bin# ls
jupyter-kernel.raku     synopsis-dan-pandas.raku     synopsis-dan.raku     test.csv     test.json     zef
jupyter-kernel.raku-j   synopsis-dan-pandas.raku-j   synopsis-dan.raku-j   test.csv-j   test.json-j   zef-j
jupyter-kernel.raku-js  synopsis-dan-pandas.raku-js  synopsis-dan.raku-js  test.csv-js  test.json-js  zef-js
jupyter-kernel.raku-m   synopsis-dan-pandas.raku-m   synopsis-dan.raku-m   test.csv-m   test.json-m   zef-m
(base) root@e4a956a998d8:/usr/share/perl6/site/bin# raku synopsis-dan-pandas.raku
a    0.042813
b    0.161430
c    0.845135
d    0.365701
e    0.217603
Name: anon, dtype: float64
d    0.365701
e    0.217603
f         NaN
g         NaN
h         NaN
i         NaN
Name: anon, dtype: float64
[0.0428134343745632 0.16142959930861056 0.8451349763429203 0.3657014364529799 0.21760269725424985]
a    0.042813
b    0.161430
c    0.845135
d    0.365701
e    0.217603
Name: anon, dtype: float64
=============================================
                   A         B         C         D
2022-01-01  0.979194  0.903654  0.537081  0.952612
2022-01-02  0.166822  0.392343  0.586934  0.221315
2022-01-03  0.601736  0.851673  0.188571  0.165916
2022-01-04  0.899416  0.423053  0.480132  0.681721
2022-01-05  0.237028  0.613430  0.045579  0.788921
2022-01-06  0.943222  0.990172  0.615224  0.537891
---------------------------------------------
   A           B  C  D      E    F
0  1  2022-01-01  1  3   test  foo
1  1  2022-01-01  1  3  train  foo
2  1  2022-01-01  1  3   test  foo
3  1  2022-01-01  1  3  train  foo
---------------------------------------------
  letter  number
0      a       1
1      b       2
  animal  letter number
0      c       3    cat
1      d       4    dog
---------------------------------------------
WARNING: unhandled Failure detected in DESTROY. If you meant to ignore it, you can mark it as handled by calling .Bool, .so, .not, or .defined methods. The Failure was:
No such symbol '<class 'numpy.int64'>'
  in block  at /usr/share/perl6/site/sources/A0EFFE63B40BC04CD8EB78CDCC7B22971E653B3A (Dan::Pandas) line 535
  in block  at /usr/share/perl6/site/sources/A0EFFE63B40BC04CD8EB78CDCC7B22971E653B3A (Dan::Pandas) line 533
  in block  at /usr/share/perl6/site/sources/A0EFFE63B40BC04CD8EB78CDCC7B22971E653B3A (Dan::Pandas) line 530
  in method TWEAK at /usr/share/perl6/site/sources/A0EFFE63B40BC04CD8EB78CDCC7B22971E653B3A (Dan::Pandas) line 516
  in method new at /usr/share/perl6/site/sources/A0EFFE63B40BC04CD8EB78CDCC7B22971E653B3A (Dan::Pandas) line 380
  in block <unit> at /usr/share/perl6/site/resources/33D910559CD097A6E5B7238BEDD1A6A24DC0F1B4 line 138
  in sub MAIN at synopsis-dan-pandas.raku line 3
  in block <unit> at synopsis-dan-pandas.raku line 1

    letter number  animal
0        a      1     NaN
1        b      2     NaN
0⋅1    cat      c     3.0
1⋅1    dog      d     4.0
(6, 4)
<Flags(allows_duplicate_labels=True)>
   2022-01-01  2022-01-02  2022-01-03  2022-01-04  2022-01-05  2022-01-06
A    0.979194    0.166822    0.601736    0.899416    0.237028    0.943222
B    0.903654    0.392343    0.851673    0.423053    0.613430    0.990172
C    0.537081    0.586934    0.188571    0.480132    0.045579    0.615224
D    0.952612    0.221315    0.165916    0.681721    0.788921    0.537891
None
None
A    23.0
B    23.0
C    23.0
D    23.0
Name: 2022-01-03, dtype: float64
                    A          B          C          D
2022-01-01   0.979194   0.903654   0.537081   0.952612
2022-01-02   0.166822   0.392343   0.586934   0.221315
2022-01-03  23.000000  23.000000  23.000000  23.000000
2022-01-04   0.899416   0.423053   0.480132   0.681721
2022-01-05   0.237028   0.613430   0.045579   0.788921
2022-01-06   0.943222   0.990172   0.615224   0.537891
```

**Comment by librasteve** [comment] 2022-06-08 08:03
so - 
the root cause is poor version control Dan and Dan::Pandas

the patch is: please install Dan and Dan::Pandas individually direct from github, like this:
```
zef --verbose install https://github.com/p6steve/raku-Dan.git
zef --verbose install https://github.com/p6steve/raku-Dan-Pandas.git
```

the fix is: bump both Dan and Dan::Pandas to v0.0.2 and re-submit to zef repository

this can take a couple of hours to get reindexed so plan is to retest regular ```zef install Dan::Pandas``` later today before closing issue

**Comment by librasteve** [comment] 2022-06-08 08:12
Dan and Dan::Pandas both bumped to v0.0.2 and fez upload done

**Comment by librasteve** [comment] 2022-06-08 10:33
new version now on https://raku.land/zef:p6steve/Dan::Pandas

zef install Dan::Pandas tests OK

**Closed as completed by librasteve** 2022-06-08 10:33 UTC
